language: perl

perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"

install:
  - cpanm --notest --quiet Dist::Zilla
  - dzil authordeps | cpanm --quiet --notest
  - cpanm --quiet --notest --installdeps .

script:
  - dzil test

